### ISSUE TITLE
differentiate 200 and 120hz camera systems

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#161] opened 2018-01-26 11:03 UTC
200hz system eye cameras can not and do not need to be focused
120hz system is adjustable in focus

**Comment by papr** [comment] 2018-01-26 11:05
Duplicate of #160, closing

**Comment by mkassner** [comment] 2018-01-26 11:20
I closed #160

**Comment by nathakits** [comment] 2018-02-01 06:38
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/167

Copytext needs checking.

**Comment by willpatera** [comment] 2018-02-01 07:04
Revised copy text and merged. Closing :smile_cat:

**Closed by willpatera** 2018-02-01 07:04 UTC
