### ISSUE TITLE
HTC Vive Add-on Setup Instructions

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#91] opened 2017-08-07 09:37 UTC
The Vive add-on setup instructions do not link to the entire playlist. It should link to all 4 videos and the playlist: https://youtu.be/Y25IdlQEehA

**Comment by nathakits** [comment] 2017-08-07 10:54
This is a problem with the youtube shortcode i did a while back ago. The problem is in the youtube lazyload js file i created to defer the loading. The Regex is only grabbing the embed video, thus the rest of the playlist is removed from the link.

**Comment by nathakits** [comment] 2017-08-08 07:04
@willpatera - another YT PR. This one fixed the issue i addressed in the PR - https://github.com/pupil-labs/docuapi/pull/40

**Comment by nathakits** [comment] 2017-08-09 03:29
Merged. Closing issue.

**Closed** 2017-08-09 04:59 UTC
